#!/bin/bash
export OSPL_HOME=$HOME/MODULES/ts_opensplice/OpenSpliceDDS/V6.4.1/HDE/x86_64.linux
export OSPL_URI=file://${OSPL_HOME}/etc/config/ospl.xml

export DDSLIB=${HOME}/APPROOT/ddslib

export LD_LIBRARY_PATH=${OSPL_HOME}/lib:${DDSLIB}:${LD_LIBRARY_PATH}
export PYTHONPATH=${DDSLIB}:${PYTHONPATH}

$@
