{% set data= load_setup_py_data() %}
package:
  name: ts-scheduler
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_scheduler = lsst.ts.scheduler:run_scheduler
 
test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-utils
    - ts-salobj {{ salobj_version }}
    - ts-scriptqueue
    - ts-observatory-model
    - ts-astrosky-model
    - ts-dateloc
    - rubin-sim =0
    - rsync
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - rs_download_data -d skybrightness,skybrightness_pre,throughputs,site_models
    - pytest -vsx

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-utils
    - ts-salobj
    - ts-observatory-model
    - ts-astrosky-model
    - ts-dateloc
    - rubin-sim =0
