name: lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install
        run: |
          $CONDA/bin/conda install -c lsstts -c conda-forge pre-commit ts-pre-commit-config=0.9 python=3.11 -y
          $CONDA/bin/generate_pre_commit_conf --skip-pre-commit-install

      - name: Run pre commit checks
        run: $CONDA/bin/pre-commit run --all
